nane: Enviroment
on: push
jobs:
  enviroment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH }}
    env:
      BRANCH: main
