name: Secrets
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRETS: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${SECRETS}"
      - run: echo "${SECRETS:0:1} ${SECRETS#?}"
